# Generated by Django 3.1.3 on 2022-04-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.TextField(default='user', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
