# Generated by Django 3.1.3 on 2022-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0004_singletodolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singletodolist',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=50),
        ),
    ]
