# Generated by Django 3.1.3 on 2022-04-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapi', '0005_auto_20220405_1445'),
    ]

    operations = [
        migrations.RenameField(
            model_name='singletodolist',
            old_name='todo_id',
            new_name='task_id',
        ),
    ]
